### ISSUE TITLE
When changing the search direction C-s/r must be pressed twice

### ISSUE THREAD

**Issue by minad** [astoff/isearch-mb#9]
When you want to change the search direction, the normal isearch changes the prompt and then requires you to press C-s/r again. Since Isearch-mb does not change the prompt (related to #7), having to press the C-s/r key twice feels awkward. Is there a way to avoid this?

**Comment by astoff** [comment]
This is customizable in Emacs 28 via the new `isearch-repeat-on-direction-change` variable. (I wouldn't say it's a canonical option to set, because the repeated C-s/r on direction change is the price you pay for being able to choose on which side of a match the cursor is when ending the search.)

> Since Isearch-mb does not change the prompt (related to #7), having to press the C-s/r key twice feels awkward.

That part I don't understand. There's still a (hollow) cursor which indicates both where you land if you end the search and the search direction.

**Comment by minad** [comment]
> That part I don't understand. There's still a (hollow) cursor which indicates both where you land if you end the search and the search direction.

No, idea tbh. I am kind of a newbie user it seems despite having used isearch for years. It is simply too complicated to grasp fully and I never bothered to understand the details. My point here is only that the behavior with the double keypress does not feel ntuitive. But if a configuration option exists in Emacs 28, this is all good! I never bothered too much about where the cursor lands, I rather correct that after jumping to the position.

**Comment by minad** [comment]
Ahhh, now I see the hollow cursor. Weird this only works in emacs -Q but not in my normal configuration. Probably I messed up some setting there.

EDIT: I got confused, I don't see the cursor indicator when isearch-mb-mode is active but I see it without isearch-mb. So maybe you need a separate cursor overlay in the isearch-mb-mode or is it necessary to temporarily activate some setting? I think there is some cursor in other window setting, which I have off.
